package pqt.dss.illustration.model.eo;

import java.sql.SQLException;

import javax.faces.context.ExternalContext;
import javax.faces.context.FacesContext;

import javax.servlet.http.HttpSession;

import oracle.jbo.AttributeList;
import oracle.jbo.Key;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.SequenceImpl;
import oracle.jbo.server.TransactionEvent;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Oct 04 14:37:38 PKT 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class DssIllustrationComImpl extends EntityImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        HdIdFk,
        CommencementDate,
        AlternationDate,
        AlternationCash,
        AlternationPayment,
        UserIdFk,
        EnterDate,
        LastUpdatedBy,
        LastUpdatedDate,
        ComIdPk,
        DssIllustrationHd;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int HDIDFK = AttributesEnum.HdIdFk.index();
    public static final int COMMENCEMENTDATE = AttributesEnum.CommencementDate.index();
    public static final int ALTERNATIONDATE = AttributesEnum.AlternationDate.index();
    public static final int ALTERNATIONCASH = AttributesEnum.AlternationCash.index();
    public static final int ALTERNATIONPAYMENT = AttributesEnum.AlternationPayment.index();
    public static final int USERIDFK = AttributesEnum.UserIdFk.index();
    public static final int ENTERDATE = AttributesEnum.EnterDate.index();
    public static final int LASTUPDATEDBY = AttributesEnum.LastUpdatedBy.index();
    public static final int LASTUPDATEDDATE = AttributesEnum.LastUpdatedDate.index();
    public static final int COMIDPK = AttributesEnum.ComIdPk.index();
    public static final int DSSILLUSTRATIONHD = AttributesEnum.DssIllustrationHd.index();

    /**
     * This is the default constructor (do not remove).
     */
    public DssIllustrationComImpl() {
    }

    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        return EntityDefImpl.findDefObject("pqt.dss.illustration.model.eo.DssIllustrationCom");
    }


    /**
     * Gets the attribute value for HdIdFk, using the alias name HdIdFk.
     * @return the value of HdIdFk
     */
    public Number getHdIdFk() {
        return (Number) getAttributeInternal(HDIDFK);
    }

    /**
     * Sets <code>value</code> as the attribute value for HdIdFk.
     * @param value value to set the HdIdFk
     */
    public void setHdIdFk(Number value) {
        setAttributeInternal(HDIDFK, value);
    }

    /**
     * Gets the attribute value for CommencementDate, using the alias name CommencementDate.
     * @return the value of CommencementDate
     */
    public Date getCommencementDate() {
        return (Date) getAttributeInternal(COMMENCEMENTDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for CommencementDate.
     * @param value value to set the CommencementDate
     */
    public void setCommencementDate(Date value) {
        setAttributeInternal(COMMENCEMENTDATE, value);
    }

    /**
     * Gets the attribute value for AlternationDate, using the alias name AlternationDate.
     * @return the value of AlternationDate
     */
    public Date getAlternationDate() {
        return (Date) getAttributeInternal(ALTERNATIONDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for AlternationDate.
     * @param value value to set the AlternationDate
     */
    public void setAlternationDate(Date value) {
        setAttributeInternal(ALTERNATIONDATE, value);
    }

    /**
     * Gets the attribute value for AlternationCash, using the alias name AlternationCash.
     * @return the value of AlternationCash
     */
    public Number getAlternationCash() {
        return (Number) getAttributeInternal(ALTERNATIONCASH);
    }

    /**
     * Sets <code>value</code> as the attribute value for AlternationCash.
     * @param value value to set the AlternationCash
     */
    public void setAlternationCash(Number value) {
        setAttributeInternal(ALTERNATIONCASH, value);
    }

    /**
     * Gets the attribute value for AlternationPayment, using the alias name AlternationPayment.
     * @return the value of AlternationPayment
     */
    public Number getAlternationPayment() {
        return (Number) getAttributeInternal(ALTERNATIONPAYMENT);
    }

    /**
     * Sets <code>value</code> as the attribute value for AlternationPayment.
     * @param value value to set the AlternationPayment
     */
    public void setAlternationPayment(Number value) {
        setAttributeInternal(ALTERNATIONPAYMENT, value);
    }

    /**
     * Gets the attribute value for UserIdFk, using the alias name UserIdFk.
     * @return the value of UserIdFk
     */
    public Number getUserIdFk() {
        return (Number) getAttributeInternal(USERIDFK);
    }

    /**
     * Sets <code>value</code> as the attribute value for UserIdFk.
     * @param value value to set the UserIdFk
     */
    public void setUserIdFk(Number value) {
        setAttributeInternal(USERIDFK, value);
    }

    /**
     * Gets the attribute value for EnterDate, using the alias name EnterDate.
     * @return the value of EnterDate
     */
    public Date getEnterDate() {
        return (Date) getAttributeInternal(ENTERDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for EnterDate.
     * @param value value to set the EnterDate
     */
    public void setEnterDate(Date value) {
        setAttributeInternal(ENTERDATE, value);
    }

    /**
     * Gets the attribute value for LastUpdatedBy, using the alias name LastUpdatedBy.
     * @return the value of LastUpdatedBy
     */
    public Number getLastUpdatedBy() {
        return (Number) getAttributeInternal(LASTUPDATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for LastUpdatedBy.
     * @param value value to set the LastUpdatedBy
     */
    public void setLastUpdatedBy(Number value) {
        setAttributeInternal(LASTUPDATEDBY, value);
    }

    /**
     * Gets the attribute value for LastUpdatedDate, using the alias name LastUpdatedDate.
     * @return the value of LastUpdatedDate
     */
    public Date getLastUpdatedDate() {
        return (Date) getAttributeInternal(LASTUPDATEDDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for LastUpdatedDate.
     * @param value value to set the LastUpdatedDate
     */
    public void setLastUpdatedDate(Date value) {
        setAttributeInternal(LASTUPDATEDDATE, value);
    }

    /**
     * Gets the attribute value for ComIdPk, using the alias name ComIdPk.
     * @return the value of ComIdPk
     */
    public Number getComIdPk() {
        return (Number) getAttributeInternal(COMIDPK);
    }

    /**
     * Sets <code>value</code> as the attribute value for ComIdPk.
     * @param value value to set the ComIdPk
     */
    public void setComIdPk(Number value) {
        setAttributeInternal(COMIDPK, value);
    }

    /**
     * @return the associated entity DssIllustrationHdImpl.
     */
    public DssIllustrationHdImpl getDssIllustrationHd() {
        return (DssIllustrationHdImpl) getAttributeInternal(DSSILLUSTRATIONHD);
    }

    /**
     * Sets <code>value</code> as the associated entity DssIllustrationHdImpl.
     */
    public void setDssIllustrationHd(DssIllustrationHdImpl value) {
        setAttributeInternal(DSSILLUSTRATIONHD, value);
    }


    /**
     * @param comIdPk key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(Number comIdPk) {
        return new Key(new Object[] { comIdPk });
    }

    /**
     * Add attribute defaulting logic in this method.
     * @param attributeList list of attribute names/values to initialize the row
     */

        protected void create(AttributeList attributeList) {
                     super.create(attributeList);
                     Date currentDate = new Date();
                     setEnterDate((Date) currentDate.getCurrentDate());
                     setLastUpdatedDate((Date) currentDate.getCurrentDate());
                     SequenceImpl seq = new SequenceImpl("DSS_ILLUSTRATION_COM_SEQ", getDBTransaction());
                     setComIdPk(seq.getSequenceNumber());
                     FacesContext fctx = FacesContext.getCurrentInstance();
                     ExternalContext ectx = fctx.getExternalContext();
                     HttpSession userSession = (HttpSession) ectx.getSession(false);
                     try {
                         setUserIdFk(new Number(userSession.getAttribute("pUserId")));
                         setLastUpdatedBy(new Number(userSession.getAttribute("pUserId")));
                     } catch (SQLException ex) {
                         setUserIdFk(new Number(0));
                         setLastUpdatedBy(new Number(0));
                     }
                 }
    /**
     * Add locking logic here.
     */
    public void lock() {
        super.lock();
    }

    /**
     * Custom DML update/insert/delete logic here.
     * @param operation the operation type
     * @param e the transaction event
     */
    protected void doDML(int operation, TransactionEvent e) {
                Date currentDate = new Date();
                if (operation == DML_UPDATE) {
                    setLastUpdatedDate((Date) currentDate.getCurrentDate());
                    FacesContext fctx = FacesContext.getCurrentInstance();
                    ExternalContext ectx = fctx.getExternalContext();
                    HttpSession userSession = (HttpSession) ectx.getSession(false);
                    try {
                        setUserIdFk(new Number(userSession.getAttribute("pUserId")));
                        setLastUpdatedBy(new Number(userSession.getAttribute("pUserId")));
                    } catch (SQLException ex) {
                        setUserIdFk(new Number(0));
                        setLastUpdatedBy(new Number(0));
                    }
                }
                super.doDML(operation, e);
            }
    }

