package pqt.dss.illustration.model.eo;

import java.sql.SQLException;

import javax.faces.context.ExternalContext;
import javax.faces.context.FacesContext;

import javax.servlet.http.HttpSession;

import oracle.jbo.AttributeList;
import oracle.jbo.Key;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.SequenceImpl;
import oracle.jbo.server.TransactionEvent;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Oct 04 14:45:34 PKT 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class DssIllustrationRpImpl extends EntityImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        HdIdFk,
        NameRp,
        CellNo,
        DateRequest,
        Branch,
        BranchComments,
        UserIdFk,
        EnterDate,
        LastUpdatedBy,
        LastUpdatedDate,
        RpIdPk,
        DssIllustrationHd;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int HDIDFK = AttributesEnum.HdIdFk.index();
    public static final int NAMERP = AttributesEnum.NameRp.index();
    public static final int CELLNO = AttributesEnum.CellNo.index();
    public static final int DATEREQUEST = AttributesEnum.DateRequest.index();
    public static final int BRANCH = AttributesEnum.Branch.index();
    public static final int BRANCHCOMMENTS = AttributesEnum.BranchComments.index();
    public static final int USERIDFK = AttributesEnum.UserIdFk.index();
    public static final int ENTERDATE = AttributesEnum.EnterDate.index();
    public static final int LASTUPDATEDBY = AttributesEnum.LastUpdatedBy.index();
    public static final int LASTUPDATEDDATE = AttributesEnum.LastUpdatedDate.index();
    public static final int RPIDPK = AttributesEnum.RpIdPk.index();
    public static final int DSSILLUSTRATIONHD = AttributesEnum.DssIllustrationHd.index();

    /**
     * This is the default constructor (do not remove).
     */
    public DssIllustrationRpImpl() {
    }

    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        return EntityDefImpl.findDefObject("pqt.dss.illustration.model.eo.DssIllustrationRp");
    }


    /**
     * Gets the attribute value for HdIdFk, using the alias name HdIdFk.
     * @return the value of HdIdFk
     */
    public Number getHdIdFk() {
        return (Number) getAttributeInternal(HDIDFK);
    }

    /**
     * Sets <code>value</code> as the attribute value for HdIdFk.
     * @param value value to set the HdIdFk
     */
    public void setHdIdFk(Number value) {
        setAttributeInternal(HDIDFK, value);
    }

    /**
     * Gets the attribute value for NameRp, using the alias name NameRp.
     * @return the value of NameRp
     */
    public String getNameRp() {
        return (String) getAttributeInternal(NAMERP);
    }

    /**
     * Sets <code>value</code> as the attribute value for NameRp.
     * @param value value to set the NameRp
     */
    public void setNameRp(String value) {
        setAttributeInternal(NAMERP, value);
    }

    /**
     * Gets the attribute value for CellNo, using the alias name CellNo.
     * @return the value of CellNo
     */
    public Number getCellNo() {
        return (Number) getAttributeInternal(CELLNO);
    }

    /**
     * Sets <code>value</code> as the attribute value for CellNo.
     * @param value value to set the CellNo
     */
    public void setCellNo(Number value) {
        setAttributeInternal(CELLNO, value);
    }

    /**
     * Gets the attribute value for DateRequest, using the alias name DateRequest.
     * @return the value of DateRequest
     */
    public Date getDateRequest() {
        return (Date) getAttributeInternal(DATEREQUEST);
    }

    /**
     * Sets <code>value</code> as the attribute value for DateRequest.
     * @param value value to set the DateRequest
     */
    public void setDateRequest(Date value) {
        setAttributeInternal(DATEREQUEST, value);
    }

    /**
     * Gets the attribute value for Branch, using the alias name Branch.
     * @return the value of Branch
     */
    public String getBranch() {
        return (String) getAttributeInternal(BRANCH);
    }

    /**
     * Sets <code>value</code> as the attribute value for Branch.
     * @param value value to set the Branch
     */
    public void setBranch(String value) {
        setAttributeInternal(BRANCH, value);
    }

    /**
     * Gets the attribute value for BranchComments, using the alias name BranchComments.
     * @return the value of BranchComments
     */
    public String getBranchComments() {
        return (String) getAttributeInternal(BRANCHCOMMENTS);
    }

    /**
     * Sets <code>value</code> as the attribute value for BranchComments.
     * @param value value to set the BranchComments
     */
    public void setBranchComments(String value) {
        setAttributeInternal(BRANCHCOMMENTS, value);
    }

    /**
     * Gets the attribute value for UserIdFk, using the alias name UserIdFk.
     * @return the value of UserIdFk
     */
    public Number getUserIdFk() {
        return (Number) getAttributeInternal(USERIDFK);
    }

    /**
     * Sets <code>value</code> as the attribute value for UserIdFk.
     * @param value value to set the UserIdFk
     */
    public void setUserIdFk(Number value) {
        setAttributeInternal(USERIDFK, value);
    }

    /**
     * Gets the attribute value for EnterDate, using the alias name EnterDate.
     * @return the value of EnterDate
     */
    public Date getEnterDate() {
        return (Date) getAttributeInternal(ENTERDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for EnterDate.
     * @param value value to set the EnterDate
     */
    public void setEnterDate(Date value) {
        setAttributeInternal(ENTERDATE, value);
    }

    /**
     * Gets the attribute value for LastUpdatedBy, using the alias name LastUpdatedBy.
     * @return the value of LastUpdatedBy
     */
    public Number getLastUpdatedBy() {
        return (Number) getAttributeInternal(LASTUPDATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for LastUpdatedBy.
     * @param value value to set the LastUpdatedBy
     */
    public void setLastUpdatedBy(Number value) {
        setAttributeInternal(LASTUPDATEDBY, value);
    }

    /**
     * Gets the attribute value for LastUpdatedDate, using the alias name LastUpdatedDate.
     * @return the value of LastUpdatedDate
     */
    public Date getLastUpdatedDate() {
        return (Date) getAttributeInternal(LASTUPDATEDDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for LastUpdatedDate.
     * @param value value to set the LastUpdatedDate
     */
    public void setLastUpdatedDate(Date value) {
        setAttributeInternal(LASTUPDATEDDATE, value);
    }

    /**
     * Gets the attribute value for RpIdPk, using the alias name RpIdPk.
     * @return the value of RpIdPk
     */
    public Number getRpIdPk() {
        return (Number) getAttributeInternal(RPIDPK);
    }

    /**
     * Sets <code>value</code> as the attribute value for RpIdPk.
     * @param value value to set the RpIdPk
     */
    public void setRpIdPk(Number value) {
        setAttributeInternal(RPIDPK, value);
    }

    /**
     * @return the associated entity DssIllustrationHdImpl.
     */
    public DssIllustrationHdImpl getDssIllustrationHd() {
        return (DssIllustrationHdImpl) getAttributeInternal(DSSILLUSTRATIONHD);
    }

    /**
     * Sets <code>value</code> as the associated entity DssIllustrationHdImpl.
     */
    public void setDssIllustrationHd(DssIllustrationHdImpl value) {
        setAttributeInternal(DSSILLUSTRATIONHD, value);
    }


    /**
     * @param rpIdPk key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(Number rpIdPk) {
        return new Key(new Object[] { rpIdPk });
    }

    /**
     * Add attribute defaulting logic in this method.
     * @param attributeList list of attribute names/values to initialize the row
     */
 
       protected void create(AttributeList attributeList) {
                     super.create(attributeList);
                     Date currentDate = new Date();
                     setEnterDate((Date) currentDate.getCurrentDate());
                     setLastUpdatedDate((Date) currentDate.getCurrentDate());
                     SequenceImpl seq = new SequenceImpl("DSS_ILLUSTRATION_RP_SEQ", getDBTransaction());
                     setRpIdPk(seq.getSequenceNumber());
                     FacesContext fctx = FacesContext.getCurrentInstance();
                     ExternalContext ectx = fctx.getExternalContext();
                     HttpSession userSession = (HttpSession) ectx.getSession(false);
                     try {
                         setUserIdFk(new Number(userSession.getAttribute("pUserId")));
                         setLastUpdatedBy(new Number(userSession.getAttribute("pUserId")));
                     } catch (SQLException ex) {
                         setUserIdFk(new Number(0));
                         setLastUpdatedBy(new Number(0));
                     }
                 }
    

    /**
     * Add locking logic here.
     */
    public void lock() {
        super.lock();
    }

    /**
     * Custom DML update/insert/delete logic here.
     * @param operation the operation type
     * @param e the transaction event
     */
    protected void doDML(int operation, TransactionEvent e) {
                Date currentDate = new Date();
                if (operation == DML_UPDATE) {
                    setLastUpdatedDate((Date) currentDate.getCurrentDate());
                    FacesContext fctx = FacesContext.getCurrentInstance();
                    ExternalContext ectx = fctx.getExternalContext();
                    HttpSession userSession = (HttpSession) ectx.getSession(false);
                    try {
                        setUserIdFk(new Number(userSession.getAttribute("pUserId")));
                        setLastUpdatedBy(new Number(userSession.getAttribute("pUserId")));
                    } catch (SQLException ex) {
                        setUserIdFk(new Number(0));
                        setLastUpdatedBy(new Number(0));
                    }
                }
                super.doDML(operation, e);
            }
    }

