package pqt.dss.illustration.model.eo;

import java.sql.SQLException;

import javax.faces.context.ExternalContext;
import javax.faces.context.FacesContext;

import javax.servlet.http.HttpSession;

import oracle.jbo.AttributeList;
import oracle.jbo.Key;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.SequenceImpl;
import oracle.jbo.server.TransactionEvent;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Oct 04 14:40:48 PKT 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class DssIllustrationDtImpl extends EntityImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        HdIdFk,
        Benefits,
        TermYears,
        DetailAmount,
        ExtraLoading,
        UserIdFk,
        EnterDate,
        LastUpdatedBy,
        LastUpdatedDate,
        DtIdPk,
        DssIllustrationHd;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int HDIDFK = AttributesEnum.HdIdFk.index();
    public static final int BENEFITS = AttributesEnum.Benefits.index();
    public static final int TERMYEARS = AttributesEnum.TermYears.index();
    public static final int DETAILAMOUNT = AttributesEnum.DetailAmount.index();
    public static final int EXTRALOADING = AttributesEnum.ExtraLoading.index();
    public static final int USERIDFK = AttributesEnum.UserIdFk.index();
    public static final int ENTERDATE = AttributesEnum.EnterDate.index();
    public static final int LASTUPDATEDBY = AttributesEnum.LastUpdatedBy.index();
    public static final int LASTUPDATEDDATE = AttributesEnum.LastUpdatedDate.index();
    public static final int DTIDPK = AttributesEnum.DtIdPk.index();
    public static final int DSSILLUSTRATIONHD = AttributesEnum.DssIllustrationHd.index();

    /**
     * This is the default constructor (do not remove).
     */
    public DssIllustrationDtImpl() {
    }

    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        return EntityDefImpl.findDefObject("pqt.dss.illustration.model.eo.DssIllustrationDt");
    }


    /**
     * Gets the attribute value for HdIdFk, using the alias name HdIdFk.
     * @return the value of HdIdFk
     */
    public Number getHdIdFk() {
        return (Number) getAttributeInternal(HDIDFK);
    }

    /**
     * Sets <code>value</code> as the attribute value for HdIdFk.
     * @param value value to set the HdIdFk
     */
    public void setHdIdFk(Number value) {
        setAttributeInternal(HDIDFK, value);
    }

    /**
     * Gets the attribute value for Benefits, using the alias name Benefits.
     * @return the value of Benefits
     */
    public String getBenefits() {
        return (String) getAttributeInternal(BENEFITS);
    }

    /**
     * Sets <code>value</code> as the attribute value for Benefits.
     * @param value value to set the Benefits
     */
    public void setBenefits(String value) {
        setAttributeInternal(BENEFITS, value);
    }

    /**
     * Gets the attribute value for TermYears, using the alias name TermYears.
     * @return the value of TermYears
     */
    public Number getTermYears() {
        return (Number) getAttributeInternal(TERMYEARS);
    }

    /**
     * Sets <code>value</code> as the attribute value for TermYears.
     * @param value value to set the TermYears
     */
    public void setTermYears(Number value) {
        setAttributeInternal(TERMYEARS, value);
    }

    /**
     * Gets the attribute value for DetailAmount, using the alias name DetailAmount.
     * @return the value of DetailAmount
     */
    public Number getDetailAmount() {
        return (Number) getAttributeInternal(DETAILAMOUNT);
    }

    /**
     * Sets <code>value</code> as the attribute value for DetailAmount.
     * @param value value to set the DetailAmount
     */
    public void setDetailAmount(Number value) {
        setAttributeInternal(DETAILAMOUNT, value);
    }

    /**
     * Gets the attribute value for ExtraLoading, using the alias name ExtraLoading.
     * @return the value of ExtraLoading
     */
    public String getExtraLoading() {
        return (String) getAttributeInternal(EXTRALOADING);
    }

    /**
     * Sets <code>value</code> as the attribute value for ExtraLoading.
     * @param value value to set the ExtraLoading
     */
    public void setExtraLoading(String value) {
        setAttributeInternal(EXTRALOADING, value);
    }

    /**
     * Gets the attribute value for UserIdFk, using the alias name UserIdFk.
     * @return the value of UserIdFk
     */
    public Number getUserIdFk() {
        return (Number) getAttributeInternal(USERIDFK);
    }

    /**
     * Sets <code>value</code> as the attribute value for UserIdFk.
     * @param value value to set the UserIdFk
     */
    public void setUserIdFk(Number value) {
        setAttributeInternal(USERIDFK, value);
    }

    /**
     * Gets the attribute value for EnterDate, using the alias name EnterDate.
     * @return the value of EnterDate
     */
    public Date getEnterDate() {
        return (Date) getAttributeInternal(ENTERDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for EnterDate.
     * @param value value to set the EnterDate
     */
    public void setEnterDate(Date value) {
        setAttributeInternal(ENTERDATE, value);
    }

    /**
     * Gets the attribute value for LastUpdatedBy, using the alias name LastUpdatedBy.
     * @return the value of LastUpdatedBy
     */
    public Number getLastUpdatedBy() {
        return (Number) getAttributeInternal(LASTUPDATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for LastUpdatedBy.
     * @param value value to set the LastUpdatedBy
     */
    public void setLastUpdatedBy(Number value) {
        setAttributeInternal(LASTUPDATEDBY, value);
    }

    /**
     * Gets the attribute value for LastUpdatedDate, using the alias name LastUpdatedDate.
     * @return the value of LastUpdatedDate
     */
    public Date getLastUpdatedDate() {
        return (Date) getAttributeInternal(LASTUPDATEDDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for LastUpdatedDate.
     * @param value value to set the LastUpdatedDate
     */
    public void setLastUpdatedDate(Date value) {
        setAttributeInternal(LASTUPDATEDDATE, value);
    }

    /**
     * Gets the attribute value for DtIdPk, using the alias name DtIdPk.
     * @return the value of DtIdPk
     */
    public Number getDtIdPk() {
        return (Number) getAttributeInternal(DTIDPK);
    }

    /**
     * Sets <code>value</code> as the attribute value for DtIdPk.
     * @param value value to set the DtIdPk
     */
    public void setDtIdPk(Number value) {
        setAttributeInternal(DTIDPK, value);
    }

    /**
     * @return the associated entity DssIllustrationHdImpl.
     */
    public DssIllustrationHdImpl getDssIllustrationHd() {
        return (DssIllustrationHdImpl) getAttributeInternal(DSSILLUSTRATIONHD);
    }

    /**
     * Sets <code>value</code> as the associated entity DssIllustrationHdImpl.
     */
    public void setDssIllustrationHd(DssIllustrationHdImpl value) {
        setAttributeInternal(DSSILLUSTRATIONHD, value);
    }


    /**
     * @param dtIdPk key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(Number dtIdPk) {
        return new Key(new Object[] { dtIdPk });
    }

    /**
     * Add attribute defaulting logic in this method.
     * @param attributeList list of attribute names/values to initialize the row
     */
 
        protected void create(AttributeList attributeList) {
                     super.create(attributeList);
                     Date currentDate = new Date();
                     setEnterDate((Date) currentDate.getCurrentDate());
                     setLastUpdatedDate((Date) currentDate.getCurrentDate());
                     SequenceImpl seq = new SequenceImpl("DSS_ILLUSTRATION_DT_SEQ", getDBTransaction());
                     setDtIdPk(seq.getSequenceNumber());
                     FacesContext fctx = FacesContext.getCurrentInstance();
                     ExternalContext ectx = fctx.getExternalContext();
                     HttpSession userSession = (HttpSession) ectx.getSession(false);
                     try {
                         setUserIdFk(new Number(userSession.getAttribute("pUserId")));
                         setLastUpdatedBy(new Number(userSession.getAttribute("pUserId")));
                     } catch (SQLException ex) {
                         setUserIdFk(new Number(0));
                         setLastUpdatedBy(new Number(0));
                     }
                 }
    

    /**
     * Add locking logic here.
     */
    public void lock() {
        super.lock();
    }

    /**
     * Custom DML update/insert/delete logic here.
     * @param operation the operation type
     * @param e the transaction event
     */
    protected void doDML(int operation, TransactionEvent e) {
                Date currentDate = new Date();
                if (operation == DML_UPDATE) {
                    setLastUpdatedDate((Date) currentDate.getCurrentDate());
                    FacesContext fctx = FacesContext.getCurrentInstance();
                    ExternalContext ectx = fctx.getExternalContext();
                    HttpSession userSession = (HttpSession) ectx.getSession(false);
                    try {
                        setUserIdFk(new Number(userSession.getAttribute("pUserId")));
                        setLastUpdatedBy(new Number(userSession.getAttribute("pUserId")));
                    } catch (SQLException ex) {
                        setUserIdFk(new Number(0));
                        setLastUpdatedBy(new Number(0));
                    }
                }
                super.doDML(operation, e);
            }
    }

