package pqt.dss.illustration.model.am.common;

import oracle.jbo.ApplicationModule;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Oct 31 11:41:19 PKT 2016
// ---------------------------------------------------------------------
public interface dssIllustrationAM extends ApplicationModule {
    void Apply();

    void DeleteCommit();

    void DssApprove();

    void Rollback();

    void callWorkflow(oracle.jbo.domain.Number p_document_id, String ApprovalType);

    void callIllustrationWorkflow(oracle.jbo.domain.Number p_document_id);
}

