package pqt.dss.illustration.model.vo.common;

import oracle.jbo.ViewObject;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Oct 31 11:45:33 PKT 2016
// ---------------------------------------------------------------------
public interface DssIllustrationHdView extends ViewObject {
    void setNVC_WfDocumentId(oracle.jbo.domain.Number value);

    void illustrationSearchUser();
}

